export async function GET() {
  return Response.json({
    generated_at: "2026-09-04T09:34:37.000Z",
    source: {
      label: "Frozen RecoveryGym evaluation and persisted safety evidence",
      seed: 42,
      synthetic: true,
    },
    system: {
      mode: "SHADOW",
      model: "observable-logistic-tlearner-v1",
      storage: "Neon Postgres",
      tests: 64,
    },
    journey: {
      total: 500,
      recovered: 263,
      stopped: 205,
      exhausted: 22,
      escalated: 10,
      cooldown_waits: 163,
      recovered_amount_paise: 63_471_115,
    },
    batch: {
      selected: 21,
      candidates: 94,
      budget_paise: 5_000,
      spent_paise: 5_000,
      expected_incremental_value_paise: 1_763_443.874,
    },
    queue: [
      { case_id: "case_0042", segment: "RETRY PRONE", amount_paise: 1_249_900, action: "RETRY_24H", expected_incremental_value_paise: 124_360, status: "ALLOW" },
      { case_id: "case_0087", segment: "LOYAL SAAS", amount_paise: 899_900, action: "ALT_PAYMENT", expected_incremental_value_paise: 91_220, status: "ALLOW" },
      { case_id: "case_0019", segment: "PRICE SENSITIVE", amount_paise: 749_900, action: "PARTIAL_PAYMENT", expected_incremental_value_paise: 76_480, status: "REVIEW" },
      { case_id: "case_0063", segment: "NEW ECOM", amount_paise: 499_900, action: "PAYMENT_LINK", expected_incremental_value_paise: 49_710, status: "ALLOW" },
      { case_id: "case_0091", segment: "RETRY PRONE", amount_paise: 319_900, action: "REMINDER", expected_incremental_value_paise: 28_840, status: "ALLOW" },
    ],
    decision: {
      case_id: "case_0042",
      segment: "RETRY PRONE",
      amount_paise: 1_249_900,
      failure_reason: "INSUFFICIENT FUNDS",
      selected_action: "RETRY_24H",
      policy_decision: "ALLOW",
      policy_reason: "POLICY_OK",
      natural_recovery_probability: 0.341,
      selected_action_probability: 0.598,
      probability_uplift: 0.257,
      intervention_cost_paise: 200,
      expected_incremental_value_paise: 124_360,
      alternatives: [
        { action: "RETRY_24H", probability: 0.598, uplift: 0.257, incremental_value_paise: 124_360, permitted: true },
        { action: "ALT_PAYMENT", probability: 0.551, uplift: 0.210, incremental_value_paise: 101_720, permitted: true },
        { action: "PAYMENT_LINK", probability: 0.507, uplift: 0.166, incremental_value_paise: 79_640, permitted: true },
        { action: "REMINDER", probability: 0.423, uplift: 0.082, incremental_value_paise: 38_920, permitted: true },
        { action: "PARTIAL_PAYMENT", probability: 0.462, uplift: 0.121, incremental_value_paise: 56_680, permitted: false },
        { action: "NO_ACTION", probability: 0.341, uplift: 0, incremental_value_paise: 0, permitted: true },
      ],
      guardrails: [
        { label: "Customer consent", value: "Contact permitted", passed: true },
        { label: "Attempts", value: "1 of 3 used", passed: true },
        { label: "Contacts", value: "1 of 3 in 7 days", passed: true },
        { label: "Retry cooldown", value: "24h elapsed", passed: true },
        { label: "Amount gate", value: "Below autonomous limit", passed: true },
      ],
      timeline: [
        { time: "09:14:02", title: "Payment failure normalized", detail: "Insufficient funds · UPI · ₹12,499", tone: "slate" },
        { time: "09:14:03", title: "Incremental value estimated", detail: "Six observable response models scored", tone: "cyan" },
        { time: "09:14:03", title: "Safety policy allowed retry", detail: "All persisted guardrails passed", tone: "emerald" },
        { time: "09:14:04", title: "Journey waiting", detail: "RETRY_24H scheduled after bounded cooldown", tone: "amber" },
      ],
    },
    learning: {
      evaluation_cases: 10_000,
      paired_seeds: 30,
      mean_additional_revenue_rupees: 1_485_657.564,
      relative_gain_pct: 11.697,
      relative_gain_ci95: { lower: 11.35, upper: 12.043 },
      seed_wins: 30,
      selected_probability_mae_pct: 5.166,
      natural_probability_mae_pct: 5.504,
      selected_brier_score: 0.2212,
      observations_per_action: 4_000,
      actions: ["NO ACTION", "REMINDER", "RETRY 24H", "PAYMENT LINK", "ALT PAYMENT", "PARTIAL PAYMENT"],
    },
    safety: {
      passed: 7,
      total: 7,
      scenarios: [
        { name: "Duplicate event", result: "Ignored", detail: "One decision and action row" },
        { name: "Customer opt-out", result: "No action", detail: "Contact interventions blocked" },
        { name: "High-value payment", result: "Approval", detail: "₹25,000 exceeded autonomous gate" },
        { name: "Attempt limit", result: "No action", detail: "Three-attempt ceiling enforced" },
        { name: "Already paid", result: "Terminal", detail: "Late failure could not reopen case" },
        { name: "Exactly-once execution", result: "One call", detail: "Duplicate delivery made no second call" },
        { name: "Audit completeness", result: "Complete", detail: "Open → decision → action → completion" },
      ],
      persistence_counts: { events: 9, cases: 6, decisions: 7, actions: 7, outcomes: 1, audits: 44 },
      audit: [
        { sequence: 1, event: "EVENT_RECEIVED", detail: "evt_exactly_once claimed by UNIQUE event ID", status: "stored" },
        { sequence: 2, event: "CASE_OPENED", detail: "pay_exactly_once entered AT_RISK", status: "stored" },
        { sequence: 3, event: "DECISION_RECORDED", detail: "ALT_PAYMENT · ALLOW · POLICY_OK", status: "stored" },
        { sequence: 4, event: "ACTION_RECORDED", detail: "Idempotency key reserved before adapter call", status: "reserved" },
        { sequence: 5, event: "ACTION_COMPLETED", detail: "Fake adapter returned plink_gauntlet_1", status: "executed" },
        { sequence: 6, event: "EVENT_COMPLETED", detail: "Event result persisted as PROCESSED", status: "complete" },
      ],
    },
  });
}
